### ISSUE TITLE
How to shutdown device?

### ISSUE THREAD

**Issue by jcf06010** [Idein/actcast-support#1]
## Description
 How to shutdown device(RaspberryPi Zero WH) except power off?
Or please add shutdwon in ACTION menu.
Can you instruct password of pi?

## Environments

- date and time of occurrence
- device type
- application
    - name
    - version
- configuration of Act and Cast

**Comment by yasuyuky** [comment]
Hi. Thanks for your feedback. 😉 

Currently, there is no shutdown command in Actcast, so you need to shut down the raspberry pi physically.
We are considering to add a function to shut down from the GUI.

**Comment by yasuyuky** [comment]
Now you can shut down devices via the web interface 🎉
