### ISSUE TITLE
How to change Wi-Fi SSID and Password?

### ISSUE THREAD

**Issue by hyamasi** [Idein/actcast-support#3]
## Description
How to change Wi-Fi SSID and Password?

## Environments

- date and time of occurrence
- device type
- application
    - name
    - version
- configuration of Act and Cast

**Comment by notogawa** [comment]
Thank you for trying Actcast.

To overwrite Wi-Fi setting, 
1. mount your micro SD card on your PC
2. prepare `wpa_supplicant.conf` with new Wi-Fi setting
    * [`wpa_supplicant.conf` setting example](https://w1.fi/cgit/hostap/plain/wpa_supplicant/wpa_supplicant.conf)
3. put `wpa_supplicant.conf` into `/path/to/mount/point/boot/`
    * for example, if you use macOS, `/Volumes/boot/wpa_supplicant.conf` will be expected one
4. unmount your micro SD card
5. put your micro SD card into Raspberry Pi and reboot it

**Comment by hyamasi** [comment]
Thanks for the advice.
I was able to change it.
