### ISSUE TITLE
Cannot send Pose Keypoints?

### ISSUE THREAD

**Issue by ryotaikeuchi** [Idein/actcast-support#4]
## Description
I want to do Pose Estimation and send the result(pose keypoints) as a webhook.
It is described as "Nothing to send" in the docs of Pose Estimation. 
I can choose "gzipped svg" as insert variable of body, but how can I use this?
I tried to send a webhook to IFTTT, but nothing received.
(trigger condition: timestamp>0 or szipped_svg != 0)

**Comment by yasuyuky** [comment]
Thank you for trying Actcast.
Pose Estimation does not send Actlog (as described in application description)
It is published just as Demo.

In the future, there is a possibility to publish an application that can send Pose information in some form, but there is no information that can be announced at this time 😉

**Comment by ryotaikeuchi** [comment]
Thank you for your reply.
I hope that it's possible to use pose information soon.
(For example, I want to develop multi-modal UI system of voice and pose... )
