### ISSUE TITLE
No gender variable in the Insert Variable list of Visitors' Age and Gender Analysis

### ISSUE THREAD

**Issue by da-take** [Idein/actcast-support#5]
Hello, I am now trying "Visitors' Age and Gender Analysis"  to send the data to the webhook.

The description shows this Act sends the following:

`{"age":26.7,"gender":"Male","timestamp":1578468809.186131}`

However, in the casts setting, I could not find "gender" in the list of "Insert Variable". 
I sent the {{data.style}} which is in the list but it seemed empty.

<img width="605" alt="スクリーンショット 2020-03-05 22 01 09" src="https://user-images.githubusercontent.com/13637208/75983952-d7af2180-5f2c-11ea-9cf7-f0e887d3967e.png">

For your reference, other data - age, device.id, etc were logged via webhook correctly.

**Comment by nineties** [comment]
Thank you very much for the report.
We’ve fixed the problem and released new version of this app: `release-20200306-01`
Please re-create the app from `New Act` and re-install it.

**Comment by da-take** [comment]
Thanks for your quick fixing!
I successfully sent them.
